version: '3.7'

networks:
  scalenet:
    ipam: 
      config: 
        - subnet: 10.50.0.0/16

services:
  config:
    build: .
    hostname: scls
    container_name: scls
    environment: 
      VERTX_CONFIG_PATH: conf/config.json
    env_file: 
      .env
    volumes:
      - ./scales/src/main/resources/conf:/opt/server/conf
    entrypoint: ["sh", "-c"]
    command: ["java -jar scales-0.1.0-all.jar run scales.verticles.MainVerticle -cluster -conf /opt/server/conf/config.json"]
    networks:
      scalenet:
        ipv4_address: 10.50.1.1
